# Generated by Django 5.2.6 on 2025-09-11 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Напишите название рассылки', max_length=200, verbose_name=' Название рассылки')),
                ('datetime_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата начала рассылки', verbose_name='Дата начала рассылки')),
                ('datetime_send', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата отправки', verbose_name='Дата отправки')),
                ('datetime_finish', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата окончания рассылки', verbose_name='Дата окончания рассылки')),
                ('periodicity', models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц'), ('year', 'раз в год')], default='year', help_text='Периодичность', max_length=20, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('launched', 'Запущена')], default='created', help_text='Статус рассылки', max_length=20, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, help_text='Активность', verbose_name='Активность')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('set_is_active', 'Может менять активность рассылки'), ('launching_mailing', 'Может запускать рассылки')],
            },
        ),
        migrations.CreateModel(
            name='Mailing_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_send', models.DateTimeField(auto_now=True, help_text='Дата и время последней попытки', verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(help_text='Статус попытки', max_length=50, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, help_text='Ответ сервера', null=True, verbose_name='Ответ сервера')),
                ('mailing', models.ForeignKey(help_text='Рассылка', on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
                ('owner', models.ForeignKey(blank=True, help_text='Владелец', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Попыткиа рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Тема письма', max_length=240, null=True, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, help_text='Заполните тело сообщения', null=True, verbose_name='Тело письма')),
                ('owner', models.ForeignKey(blank=True, help_text='Владелец', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'permissions': [('set_update', 'Может менять сообщения')],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение рассылки'),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Электронная почта', max_length=254, verbose_name='Электронная почта')),
                ('name', models.CharField(help_text='ФИО', max_length=200, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, help_text='Комментарий', null=True, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipient',
            field=models.ManyToManyField(help_text='Получатели рассылки', to='mailing.recipient', verbose_name='Получатели рассылки'),
        ),
    ]
